# Python Programming Basic Assignment
## Programming Assignment_8

<b>Q1. </b>Write a Python Program to Add Two Matrices?

In [1]:
import numpy as np
a = np.array([[1,3],[6,8]])
b = np.array([[2,4],[2,5]])
print("Matrix a = \n{}".format(a))
print("Matrix b = \n{}".format(b))
print("Addition Result = \n{}".format(a+b))

Matrix a = 
[[1 3]
 [6 8]]
Matrix b = 
[[2 4]
 [2 5]]
Addition Result = 
[[ 3  7]
 [ 8 13]]


<b>Q2. </b>Write a Python Program to Multiply Two Matrices?

In [2]:
import numpy as np
a = np.array([[1,3],[6,8]])
b = np.array([[2,4],[2,5]])
print("Matrix a = \n{}".format(a))
print("Matrix b = \n{}".format(b))
print("Multiplication Result = \n{}".format(a.dot(b)))

Matrix a = 
[[1 3]
 [6 8]]
Matrix b = 
[[2 4]
 [2 5]]
Multiplication Result = 
[[ 8 19]
 [28 64]]


<b>Q3. </b>Write a Python Program to Transpose a Matrix?

In [3]:
import numpy as np
a = np.array([[1,3],[6,8]])
print("Matrix = \n{}".format(a))
print("Transpose = \n{}".format(a.T))

Matrix = 
[[1 3]
 [6 8]]
Transpose = 
[[1 6]
 [3 8]]


<b>Q4. </b>Write a Python Program to Sort Words in Alphabetic Order?

In [4]:
l = [i.lower() for i in input("Enter some words : ").split()]
print("Sorted words : {}".format(sorted(l)))

Enter some words : This is to check if it sort according to alphabetic order
Sorted words : ['according', 'alphabetic', 'check', 'if', 'is', 'it', 'order', 'sort', 'this', 'to', 'to']


<b>Q5. </b>Write a Python Program to Remove Punctuation From a String?

In [5]:
import string
my_str = input("Enter your statement : ")
print("After removing the punctuation : ",end = " ")
for i in my_str:
    if i in string.punctuation:
        continue
    else:
        print(i,end = "")

Enter your statement : Hello @just !!! check (if &= all punctuation is removed...
After removing the punctuation :  Hello just  check if  all punctuation is removed